plugins:
  - jemoji
  - jekyll-paginate
repository: kimyyx/go-frontend-go
theme: jekyll-theme-cayman
title: Go frontend Go
description: 资讯 & 知识点 & 面试题 for 前端
github:
  is_project_page: false
  repository_name: Go frontend Go
  repository_url: https://github.com/kimyyx/go-frontend-go
google_analytics: UA-130710568-1

# excerpt_separator: <!--more-->

paginate: 10
paginate_path: /blog/page:num/
