plugins:
  - jemoji
  - jekyll-paginate
repository: kimyyx/go-frontend-go
theme: jekyll-theme-hacker
title: 歪歪叉的博客
description: 梦想是诗酒和远方，苟且是键盘和代码，还有那看不完的书
github:
  is_project_page: false
  repository_name: Go frontend Go
  repository_url: https://github.com/kimyyx/go-frontend-go
google_analytics: UA-130710568-1

# excerpt_separator: <!--more-->

paginate: 10
paginate_path: /blog/page:num/
